// Example: functionDescriptions.js
const functionDescriptions = {
    "01": "Blank Escutcheon Plate",
    "04": "Night Latch: Key retracts latch bolt. Key does all the work. Can be cylinder only without ET Trim",
    "10": "Exit Only: No outside trim or lever required. Can have ET Trim but no Spindle. Pull Plate often used.",
    "06": "Storeroom: Key Locks/Unlocks outside lever, key removable only when locked (always locked).",
    "13": "Classroom: Key locks/unlocks outside lever (can leave unlocked all day then lock at night).",
    "15": "Passage: Latch retracted by lever. Outside lever is never locked. ",
    "28": "Passage (Pull Trim Only): Latch retracted by Pull Thumbpiece from either side. Outside Pull is never locked.",
    "40": "Free Wheeling Exit Only: Lever used as pull (Has ET Trim but no Spindle) | Or will have no trim at all",
    "43": "Free Wheeling Classroom: Key locks/unlocks outside lever (can leave unlocked all day then lock at night but lever spins).",
    "44": "Free Wheeling Night Latch: Key retracts latch bolt.",
    "46": "Free Wheeling Storeroom: Key Locks/Unlocks outside lever, key removable only when locked (always locked). Lever Spins)",
    "62": "Storeroom (Pull Trim Only): Key unlocks Thumbpiece, Thumbpiece retracts latch/ Thumbpiece relocks when key is removed ",
    "63": "Classroom (Pull Trim Only): Key Locks/Unlocks outside Thumbpiece (can leave unlocked all day then lock at night",
    "66": "Classroom Intruder (Pull Trim Only): Key Outside Retracts Latch; Key Inside Unlocks/Locks Outside Trim",
    "73": "Fail Safe: No Cylinder -- Power On = Lever Locked, Power Off = Lever Unlocked. (Power Failure = Unlocked)",
    "74": "Fail Secure: No Cylinder -- Power On = Lever Unlocked, Power Off = Lever Locked. (Power Failure = Locked)",
    "75": "Fail Safe: Has a Cylinder -- Power On = Lever Locked, Power Off = Lever Unlocked. (Power Failure = Unlocked) | Key Retracts Latch",
    "76": "Fail Secure: Has a Cylinder -- Power On = Lever Unlocked, Power Off = Lever Locked. (Power Failure = Locked) | Key Retracts Latch",
    "28K": "Night Latch: Key in Lever Retracts Latchbolt",
    "28N": "Storeroom: Leever only works when key is in cylinder and turned",
    "28D": "Dummy: Lever rigid at all times & no outside functionality (or no lever at all)",
    "28C": "Entrance/Classroom: Key in Lever locks/unlocks lever",
    "28L": "Passage: Latchbolt always operated by lever and never locked",
    "814": "Night Latch: Key retracts latch, Has Pull",
    "810": "Exit Only With Pull (Dummy): Outside Pull only for when device is dogged down",
    "802": "Exit Only : Blank Plate to cover lever/pull prep",
  };
  export default functionDescriptions;